language: java
jdk:
  - oraclejdk8
sudo: true
install: true
script: travis/mvn-build.sh
env:
  global:
    - GPG_EXECUTABLE: gpg2
    - GPG_USE_AGENT: false
    - secure: "UHZ7ZrSqLxaudfCyfGfNaeHbIrv/72RKizWj3Zo8iwntl74qht145qkPzVUvV5aBbMlKDU7WNP5Q3tdH6Bb9/xsTvmFBP0h3CnHNq+9DPfltkynYTO451BLMF/6mcj3OzAcc/KwDCErjNdYQ5+WEgcSiYe4RKcZ3r8AssziVKAgkprPk2Xy4ASWNX+Zy/y2GHxVuYwbrUFeLAYYJcRJUgKL8xTM9vuVv8uKPAOl0qJxXG8IuKnxuNO11WT6RT8ssBd1bgDkAFLXk1CoJjiZXhw7iZxX9iLcPmpLBwCn/9U3gKb6/DB+T/Df33UgFjKYcnI4u760GCIX1JxH/ghxaAYb64l9lXIxO/olHeE021CZK6ybD6Y/s5iW791fb+w31/ZPDJjSRNskA1nV3+RgKFVd/DNPu/cGKzp9jzTiO1tpMiIaArIQ4pCgOwBIT6WVpPyXWDXnC5NzI0JVJmbv6P11eUaHiNhxO+EmSCdBc0WUUvHiIKJKyRi8K//m2ATff8IACu4Xk7DJRx9rnCo6PK/Wndk6+5hQ3rwfzN77jICVGPdRFB8igozLop5g4ftUCcNRBolxBtylH/I8F3TaYbpfSadEy3l3Bu4XVTdmW7QHn+mrqODk3Rm4OQ5E1z6wMGDa4OxBg5oBgTLKOuifTP19xm1SNXOcRZ1ri1xLi89o="
before_install:
  - openssl aes-256-cbc -K $encrypted_11fec54ac905_key -iv $encrypted_11fec54ac905_iv -in travis/GPG_KEY.asc.enc -out travis/GPG_KEY.asc -d
  - gpg2 --batch --import travis/GPG_KEY.asc
addons:
  apt:
    packages:
      - gnupg2
